[package]
name = "litemd"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
eframe = "=0.30.0"
egui = "=0.30.0"
egui_commonmark = "=0.19.0"
env_logger = "0.11"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
